-- ==========================================
-- CREACION TABLA USUARIO
-- ==========================================

CREATE TABLE USUARIO (
                         ID UUID NOT NULL,
                         NOMBRE VARCHAR(255) NOT NULL,
                         EMAIL VARCHAR(255) NOT NULL,
                         PASSWORD VARCHAR(255) NOT NULL,
                         CREATED TIMESTAMP NOT NULL,
                         MODIFIED TIMESTAMP NOT NULL,
                         LAST_LOGIN TIMESTAMP NOT NULL,
                         TOKEN VARCHAR(1000) NOT NULL,
                         IS_ACTIVE BOOLEAN NOT NULL,

                         ```
                         CONSTRAINT PK_USUARIO
                             PRIMARY KEY (ID),

                         CONSTRAINT UK_USUARIO_EMAIL
                             UNIQUE (EMAIL)
                         ```

);

-- ==========================================
-- CREACION TABLA TELEFONOS
-- ==========================================

CREATE TABLE TELEFONOS (
                           ID BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                           NUMERO VARCHAR(255) NOT NULL,
                           CODIGO_CIUDAD VARCHAR(255) NOT NULL,
                           CODIGO_PAIS VARCHAR(255) NOT NULL,
                           USUARIO_ID UUID,

                           ```
                           CONSTRAINT PK_TELEFONOS
                               PRIMARY KEY (ID),

                           CONSTRAINT FK_TELEFONOS_USUARIO
                               FOREIGN KEY (USUARIO_ID)
                               REFERENCES USUARIO(ID)
                           ```

);
